import type { Metadata } from 'next';
import { Noto_Sans_TC, Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
});

const notoSansTC = Noto_Sans_TC({
  variable: '--font-noto-sans-tc',
  preload: false,
});

export const metadata: Metadata = {
  title: 'StyleCue',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-TW"
      className={`${plusJakartaSans.variable} ${notoSansTC.variable} h-full antialiased`}
    >
      <body className="flex min-h-full justify-center bg-zinc-200 font-sans">
        <div className="flex w-full max-w-md flex-col bg-surface-base">{children}</div>
      </body>
    </html>
  );
}
